# Data Cleaning
## 01 Import Libraries
## 02 Import Economy and Growth csv
## 03 Extract Relevant Rows for Study
### a) Extract required variables and copy the rows into a new dataframe
### b) Missing data and initial consistency checks
### c) Initial aggregations
### d) Interpolate Data
### e) Tidy Data Principles

## 01 Import Libraries

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## 02 Import Economy and Growth csv

In [3]:
# import dataframe

pathData = r'C:\Users\Michael\Desktop\Career Foundry\02 Data Immersion Course\06 Advanced Analytics and Dashboard Design\00 Data'
WB_poverty = pd.read_csv(os.path.join(pathData, 'World Bank Poverty', 'poverty.csv'))

## 03 Extract Relevant Rows for Study
### a) The file contains a column called "Indicator Code" and has an entry for each country. There are 254 indicators, but only the following four will be used for the study, as it is currentl understood:

| INDICATOR_CODE    | INDICATOR_NAME                                                                             |
|:------------------|:-------------------------------------------------------------------------------------------|
| SI.POV.NAHC		| Poverty headcount ratio at national poverty lines (% of population)                        |
| SI.POV.UMIC	    | Poverty headcount ratio at \$6.85 a day (2017 PPP) (\% of population)                       |
| SI.POV.DDAY		| Poverty headcount ratio at \$2.15 a day (2017 PPP) (\% of population)                      |
| SI.POV.LMIC	    | Poverty headcount ratio at \$3.65 a day (2017 PPP) (\% of population)                       |
| SI.POV.GINI		| Gini index                                                                                 |


The process to extract thesee will be as follows:
* All indicators other than these are to be dropped.
* The remaing will be saved as a new df (WB_encon_GDP_GNI)

In [4]:
# make list of the required Indicator Codes
poverty_indicators = [ 'SI.POV.NAHC',
                    'SI.POV.UMIC',
                    'SI.POV.DDAY',
                    'SI.POV.LMIC',
                    'SI.POV.GINI'
                    ]

In [5]:
# if the Indicators Variable is not in the econ_indicators list then the rown is to be dropped
# there new df is to be saved as WB_econ_GDP_GNI

WB_poverty_req = WB_poverty[WB_poverty['Indicator Code'].isin(poverty_indicators)]

In [6]:
#Check that the correct values have been selected
WB_poverty_req.head(100)

Country Name Country Code  \
5                          Aruba          ABW   
6                          Aruba          ABW   
16                         Aruba          ABW   
17                         Aruba          ABW   
19                         Aruba          ABW   
34   Africa Eastern and Southern          AFE   
35   Africa Eastern and Southern          AFE   
45   Africa Eastern and Southern          AFE   
46   Africa Eastern and Southern          AFE   
48   Africa Eastern and Southern          AFE   
63                   Afghanistan          AFG   
64                   Afghanistan          AFG   
74                   Afghanistan          AFG   
75                   Afghanistan          AFG   
77                   Afghanistan          AFG   
92    Africa Western and Central          AFW   
93    Africa Western and Central          AFW   
103   Africa Western and Central          AFW   
104   Africa Western and Central          AFW   
106   Africa Western and Central          AFW   
121                       Angola          AGO   
122                       Angola          AGO   
132                       Angola          AGO   
133                       Angola          AGO   
135                       Angola          AGO   
150                      Albania          ALB   
151                      Albania          ALB   
161                      Albania          ALB   
162                      Albania          ALB   
164                      Albania          ALB   
179                      Andorra          AND   
180                      Andorra          AND   
190                      Andorra          AND   
191                      Andorra          AND   
193                      Andorra          AND   
208                   Arab World          ARB   
209                   Arab World          ARB   
219                   Arab World          ARB   
220                   Arab World          ARB   
222                   Arab World          ARB   
237         United Arab Emirates          ARE   
238         United Arab Emirates          ARE   
248         United Arab Emirates          ARE   
249         United Arab Emirates          ARE   
251         United Arab Emirates          ARE   
266                    Argentina          ARG   
267                    Argentina          ARG   
277                    Argentina          ARG   
278                    Argentina          ARG   
280                    Argentina          ARG   
295                      Armenia          ARM   
296                      Armenia          ARM   
306                      Armenia          ARM   
307                      Armenia          ARM   
309                      Armenia          ARM   
324               American Samoa          ASM   
325               American Samoa          ASM   
335               American Samoa          ASM   
336               American Samoa          ASM   
338               American Samoa          ASM   
353          Antigua and Barbuda          ATG   
354          Antigua and Barbuda          ATG   
364          Antigua and Barbuda          ATG   
365          Antigua and Barbuda          ATG   
367          Antigua and Barbuda          ATG   
382                    Australia          AUS   
383                    Australia          AUS   
393                    Australia          AUS   
394                    Australia          AUS   
396                    Australia          AUS   
411                      Austria          AUT   
412                      Austria          AUT   
422                      Austria          AUT   
423                      Austria          AUT   
425                      Austria          AUT   
440                   Azerbaijan          AZE   
441                   Azerbaijan          AZE   
451                   Azerbaijan          AZE   
452                   Azerbaijan          AZE   
454                   Azerbaijan          AZE   
469                      Burundi          BDI   
47

In [7]:
WB_poverty_req.shape

(1330, 67)

The economic data is only avaliable from 1996 to 2021. These data will first be trimmed to fit. There is no need to run tests on data that will not be used.

In [8]:
for n in range(1960, 1996):
    WB_poverty_req.drop(columns=[str(n)], inplace=True)

WB_poverty_req.drop(columns=['2022'], inplace=True)

C:\Users\Michael\AppData\Local\Temp\ipykernel_43912\755752409.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WB_poverty_req.drop(columns=[str(n)], inplace=True)
C:\Users\Michael\AppData\Local\Temp\ipykernel_43912\755752409.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WB_poverty_req.drop(columns=[str(n)], inplace=True)
C:\Users\Michael\AppData\Local\Temp\ipykernel_43912\755752409.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-

### b) Missing data and initial consistency checks

In [9]:
# Change display to 2dp floats
pd.options.display.float_format = '{:.2f}'.format

In [10]:
# check for duplicates
WB_poverty_req[WB_poverty_req.duplicated()]

Empty DataFrame
Columns: [Country Name, Country Code, Indicator Name, Indicator Code, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]
Index: []

No duplicates found

### c) Perform aggregations

In [11]:
# making a list of all the years to use later
years = []
for n in range(1996, 2022):
    years.append(str(n))
    
print(years)

['1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']


In [12]:
# find the max value for each type
WB_poverty_req.groupby('Indicator Name').max(years)

1996  1997  1998  1999  \
Indicator Name                                                               
Gini index                                         59.90 65.80 59.60 59.00   
Poverty headcount ratio at $2.15 a day (2017 PP... 82.70 69.40 79.90 68.70   
Poverty headcount ratio at $3.65 a day (2017 PP... 91.80 89.00 94.20 90.40   
Poverty headcount ratio at $6.85 a day (2017 PP... 97.20 98.00 98.50 99.20   
Poverty headcount ratio at national poverty lin...   NaN   NaN   NaN   NaN   

                                                    2000  2001  2002  2003  \
Indicator Name                                                               
Gini index                                         61.60 58.40 64.70 63.30   
Poverty headcount ratio at $2.15 a day (2017 PP... 84.00 71.00 80.60 81.50   
Poverty headcount ratio at $3.65 a day (2017 PP... 95.50 86.20 94.20 94.60   
Poverty headcount ratio at $6.85 a day (2017 PP... 99.40 96.00 99.10 99.10   
Poverty headcount ratio at national poverty lin... 69.00 70.80 64.70 54.00   

                                                    2004  2005  2006  2007  \
Indicator Name                                                               
Gini index                                         58.10 64.80 57.50 55.80   
Poverty headcount ratio at $2.15 a day (2017 PP... 91.50 80.50 71.80 78.90   
Poverty headcount ratio at $3.65 a day (2017 PP... 97.60 92.80 90.50 93.00   
Poverty headcount ratio at $6.85 a day (2017 PP... 99.70 98.10 98.20 97.90   
Poverty headcount ratio at national poverty lin... 69.30 73.20 76.80 50.40   

                                                    2008  2009  2010  2011  \
Indicator Name                                                               
Gini index                                         63.00 61.00 63.40 53.50   
Poverty headcount ratio at $2.15 a day (2017 PP... 70.80 52.60 80.20 60.60   
Poverty headcount ratio at $3.65 a day (2017 PP... 89.60 80.00 92.40 88.30   
Poverty headcount ratio at $6.85 a day (2017 PP... 97.00 95.90 98.10 97.70   
Poverty headcount ratio at national poverty lin... 62.10 63.00 71.70 62.40   

                                                    2012  2013  2014  2015  \
Indicator Name                                                               
Gini index                                         53.40 52.70 63.00 59.10   
Poverty headcount ratio at $2.15 a day (2017 PP... 80.70 65.10 64.60 60.80   
Poverty headcount ratio at $3.65 a day (2017 PP... 92.40 86.70 83.10 78.10   
Poverty headcount ratio at $6.85 a day (2017 PP... 98.20 96.50 96.70 94.20   
Poverty headcount ratio at national poverty lin... 70.70 64.90 59.30 54.40   

                                                    2016  2017  2018  2019  \
Indicator Name                                                               
Gini index                                         54.60 53.30 53.90 53.50   
Poverty headcount ratio at $2.15 a day (2017 PP... 67.30 45.30 50.90 74.40   
Poverty headcount ratio at $3.65 a day (2017 PP... 87.30 72.70 81.20 89.10   
Poverty headcount ratio at $6.85 a day (2017 PP... 96.80 92.40 95.00 97.30   
Poverty headcount ratio at national poverty lin... 82.30 55.50 56.80 50.70   

                                                    2020  2021  
Indicator Name                                                  
Gini index                                         53.50 52.90  
Poverty headcount ratio at $2.15 a day (2017 PP... 35.00 65.70  
Poverty headcount ratio at $3.65 a day (2017 PP... 68.60 85.80  
Poverty headcount ratio at $6.85 a day (2017 PP... 91.00 96.20  
Poverty headcount ratio at national poverty lin... 53.40 68.80

All max values are consistent with expectation

In [13]:
# find the min value for each type
WB_poverty_req.groupby('Indicator Name').min(years)

1996  1997  1998  1999  \
Indicator Name                                                               
Gini index                                         25.80 26.80 28.10 28.10   
Poverty headcount ratio at $2.15 a day (2017 PP...  0.00  0.00  0.00  0.00   
Poverty headcount ratio at $3.65 a day (2017 PP...  0.00  0.00  0.00  0.00   
Poverty headcount ratio at $6.85 a day (2017 PP...  0.20  0.00  0.00  0.00   
Poverty headcount ratio at national poverty lin...   NaN   NaN   NaN   NaN   

                                                    2000  2001  2002  2003  \
Indicator Name                                                               
Gini index                                         23.80 28.70 25.30 25.30   
Poverty headcount ratio at $2.15 a day (2017 PP...  0.00  0.00  0.00  0.00   
Poverty headcount ratio at $3.65 a day (2017 PP...  0.00  0.00  0.00  0.10   
Poverty headcount ratio at $6.85 a day (2017 PP...  0.00  0.00  0.00  0.20   
Poverty headcount ratio at national poverty lin... 15.30 16.90 10.80 10.00   

                                                    2004  2005  2006  2007  \
Indicator Name                                                               
Gini index                                         24.80 24.60 24.40 24.40   
Poverty headcount ratio at $2.15 a day (2017 PP...  0.00  0.00  0.00  0.00   
Poverty headcount ratio at $3.65 a day (2017 PP...  0.00  0.00  0.00  0.00   
Poverty headcount ratio at $6.85 a day (2017 PP...  0.10  0.10  0.00  0.00   
Poverty headcount ratio at national poverty lin...  9.70  9.60  8.90  7.70   

                                                    2008  2009  2010  2011  \
Indicator Name                                                               
Gini index                                         23.70 24.80 24.80 24.60   
Poverty headcount ratio at $2.15 a day (2017 PP...  0.00  0.00  0.00  0.00   
Poverty headcount ratio at $3.65 a day (2017 PP...  0.00  0.00  0.00  0.00   
Poverty headcount ratio at $6.85 a day (2017 PP...  0.00  0.10  0.10  0.10   
Poverty headcount ratio at national poverty lin...  6.10  5.40  5.20  5.50   

                                                    2012  2013  2014  2015  \
Indicator Name                                                               
Gini index                                         24.70 24.60 24.00 25.40   
Poverty headcount ratio at $2.15 a day (2017 PP...  0.00  0.00  0.00  0.00   
Poverty headcount ratio at $3.65 a day (2017 PP...  0.00  0.00  0.00  0.00   
Poverty headcount ratio at $6.85 a day (2017 PP...  0.00  0.00  0.10  0.10   
Poverty headcount ratio at national poverty lin...  6.00  4.80  4.80  5.10   

                                                    2016  2017  2018  2019  \
Indicator Name                                                               
Gini index                                         24.80 23.20 24.60 23.20   
Poverty headcount ratio at $2.15 a day (2017 PP...  0.00  0.00  0.00  0.00   
Poverty headcount ratio at $3.65 a day (2017 PP...  0.00  0.00  0.00  0.00   
Poverty headcount ratio at $6.85 a day (2017 PP...  0.10  0.00  0.10  0.10   
Poverty headcount ratio at national poverty lin...  4.50  3.10  1.70  0.60   

                                                    2020  2021  
Indicator Name                                                  
Gini index                                         24.00 25.70  
Poverty headcount ratio at $2.15 a day (2017 PP...  0.00  0.00  
Poverty headcount ratio at $3.65 a day (2017 PP...  0.00  0.30  
Poverty headcount ratio at $6.85 a day (2017 PP...  0.00  1.00  
Poverty headcount ratio at national poverty lin...  0.00  5.20

All min values are consistent with expectation

Find the mean values of each year

In [14]:
WB_poverty_req.groupby('Indicator Name').mean(years)

1996  1997  1998  1999  \
Indicator Name                                                               
Gini index                                         41.45 43.05 42.78 42.63   
Poverty headcount ratio at $2.15 a day (2017 PP... 22.64 18.81 23.86 21.72   
Poverty headcount ratio at $3.65 a day (2017 PP... 38.27 32.17 39.68 37.12   
Poverty headcount ratio at $6.85 a day (2017 PP... 56.51 48.44 58.17 55.31   
Poverty headcount ratio at national poverty lin...   NaN   NaN   NaN   NaN   

                                                    2000  2001  2002  2003  \
Indicator Name                                                               
Gini index                                         40.60 42.25 40.99 39.24   
Poverty headcount ratio at $2.15 a day (2017 PP... 18.42 20.09 19.66 16.54   
Poverty headcount ratio at $3.65 a day (2017 PP... 32.05 36.86 36.16 30.65   
Poverty headcount ratio at $6.85 a day (2017 PP... 48.52 56.41 57.08 48.71   
Poverty headcount ratio at national poverty lin... 36.42 42.67 34.46 25.63   

                                                    2004  2005  2006  2007  \
Indicator Name                                                               
Gini index                                         37.85 39.00 37.76 36.48   
Poverty headcount ratio at $2.15 a day (2017 PP... 12.15 13.69  9.44 10.14   
Poverty headcount ratio at $3.65 a day (2017 PP... 24.29 26.09 18.85 20.62   
Poverty headcount ratio at $6.85 a day (2017 PP... 41.48 43.32 34.80 35.51   
Poverty headcount ratio at national poverty lin... 25.58 28.44 25.73 23.69   

                                                    2008  2009  2010  2011  \
Indicator Name                                                               
Gini index                                         37.52 37.54 36.44 36.19   
Poverty headcount ratio at $2.15 a day (2017 PP...  7.93  9.15  9.78  8.78   
Poverty headcount ratio at $3.65 a day (2017 PP... 16.66 19.21 20.01 18.14   
Poverty headcount ratio at $6.85 a day (2017 PP... 31.41 35.12 35.64 32.70   
Poverty headcount ratio at national poverty lin... 23.09 23.07 25.47 22.62   

                                                    2012  2013  2014  2015  \
Indicator Name                                                               
Gini index                                         36.31 36.46 36.55 36.72   
Poverty headcount ratio at $2.15 a day (2017 PP...  7.69  5.62  6.77  7.08   
Poverty headcount ratio at $3.65 a day (2017 PP... 16.83 12.97 15.60 16.42   
Poverty headcount ratio at $6.85 a day (2017 PP... 33.09 26.68 30.23 31.99   
Poverty headcount ratio at national poverty lin... 21.04 21.70 24.51 22.22   

                                                    2016  2017  2018  2019  \
Indicator Name                                                               
Gini index                                         36.18 35.51 35.71 35.21   
Poverty headcount ratio at $2.15 a day (2017 PP...  6.94  4.70  6.67  5.35   
Poverty headcount ratio at $3.65 a day (2017 PP... 14.73 11.70 16.15 11.73   
Poverty headcount ratio at $6.85 a day (2017 PP... 28.12 25.59 30.87 25.21   
Poverty headcount ratio at national poverty lin... 23.94 20.26 23.23 19.57   

                                                    2020  2021  
Indicator Name                                                  
Gini index                                         35.03 40.51  
Poverty headcount ratio at $2.15 a day (2017 PP...  2.71  7.29  
Poverty headcount ratio at $3.65 a day (2017 PP...  8.24 18.12  
Poverty headcount ratio at $6.85 a day (2017 PP... 20.15 39.17  
Poverty headcount ratio at national poverty lin... 19.81 20.60

The mean values are all consistent with the expectations of the variables (e.g. percentages are in the range 0-100)

### d) Interpolate Data

There are many missing values, to get an estimated value for these data linear interpolation can be used.
Before interpolating a flag will be made to say that the row has had interpolated data.
Interpolation will only happen if there is data with no more than 5 consecutive years of the missing (20% of total timeframe).

In [15]:
# make a dataframe with only the numerical information
WB_poverty_req_interpolated = WB_poverty_req[WB_poverty_req.columns.intersection(years)]
WB_poverty_req_interpolated.head()

1996  1997  1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  \
5    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
6    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
16   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
17   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
19   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

    2008  2009  2010  2011  2012  2013  2014  2015  2016  2017  2018  2019  \
5    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
6    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
16   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
17   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
19   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

    2020  2021  
5    NaN   NaN  
6    NaN   NaN  
16   NaN   NaN  
17   NaN   NaN  
19   NaN   NaN

In [16]:
#interpolate the figures in the numerical dataframe
WB_poverty_req_interpolated = WB_poverty_req_interpolated.interpolate(method='linear',
                                                            axis=1,
                                                            inplace=False,
                                                            limit_direction = 'both',
                                                            limit_area=None)

In [17]:
# check the interpolated values
WB_poverty_req_interpolated

1996  1997  1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  \
5      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
6      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
16     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
17     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
19     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
34     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
35     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
45     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
46     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
48     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
63     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
64   33.70 33.70 33.70 33.70 33.70 33.70 33.70 33.70 33.70 33.70 33.70 33.70   
74     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
75     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
77     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
92     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
93     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
103    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
104    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
106    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
121  67.20 67.20 67.20 67.20 67.20 67.44 67.67 67.91 68.15 68.39 68.62 68.86   
122  32.30 32.30 32.30 32.30 32.30 32.30 32.30 32.30 32.30 32.30 32.30 32.30   
132  39.50 39.50 39.50 39.50 39.50 39.27 39.05 38.83 38.60 38.38 38.15 37.93   
133  52.00 52.00 52.00 52.00 52.00 50.84 49.67 48.51 47.35 46.19 45.03 43.86   
135  21.40 21.40 21.40 21.40 21.40 20.55 19.70 18.85 18.00 17.15 16.30 15.45   
150  47.90 48.60 49.30 50.00 50.70 51.40 52.10 48.20 44.30 40.40 38.07 35.73   
151  25.40 25.40 25.40 25.40 25.40 25.40 25.40 23.10 20.80 18.50 18.97 19.45   
161   8.90  9.32  9.73 10.15 10.57 10.98 11.40 10.03  8.67  7.30  6.17  5.03   
162  27.00 27.78 28.57 29.35 30.13 30.92 31.70 31.33 30.97 30.60 30.40 30.20   
164   0.50  0.60  0.70  0.80  0.90  1.00  1.10  0.93  0.77  0.60  0.47  0.33   
179    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
180    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
190    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
191    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
193    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
208    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
209    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
219    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
220    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
222    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
237   0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00   
238    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
248   0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00   
249  32.50 32.50 32.50 32.50 32.50 32.50 32.50 32.50 32.50 32.50 32.50 32.50   
251   0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00   
266  22.40 21.30 23.30 24.20 26.30 31.10 44.40 29.60 24.70 20.80 16.80 15.40   
267  30.30 30.30 30.30 30.30 30.30 30.30 30.30 30.30 30.30 30.30 30.30 30.30   
277   8.30  7.80  8.30  8.90 10.70 15.40 24.00 12.50  9.60  7.90  5.90  4.90   
278  49.50 49.10 50.70 49.80 51.10 53.30 53.80 50.90 48.40 47.70 46.30 46.20   
280   

In [18]:
# Re-attach the row headers
WB_poverty_req_headers = WB_poverty_req[
                                    WB_poverty_req.columns.intersection([
                                                'Country Name',
                                                'Country Code',
                                                'Indicator Name',
                                                'Indicator Code'])]
WB_poverty_req_headers.head(50)

Country Name Country Code  \
5                          Aruba          ABW   
6                          Aruba          ABW   
16                         Aruba          ABW   
17                         Aruba          ABW   
19                         Aruba          ABW   
34   Africa Eastern and Southern          AFE   
35   Africa Eastern and Southern          AFE   
45   Africa Eastern and Southern          AFE   
46   Africa Eastern and Southern          AFE   
48   Africa Eastern and Southern          AFE   
63                   Afghanistan          AFG   
64                   Afghanistan          AFG   
74                   Afghanistan          AFG   
75                   Afghanistan          AFG   
77                   Afghanistan          AFG   
92    Africa Western and Central          AFW   
93    Africa Western and Central          AFW   
103   Africa Western and Central          AFW   
104   Africa Western and Central          AFW   
106   Africa Western and Central          AFW   
121                       Angola          AGO   
122                       Angola          AGO   
132                       Angola          AGO   
133                       Angola          AGO   
135                       Angola          AGO   
150                      Albania          ALB   
151                      Albania          ALB   
161                      Albania          ALB   
162                      Albania          ALB   
164                      Albania          ALB   
179                      Andorra          AND   
180                      Andorra          AND   
190                      Andorra          AND   
191                      Andorra          AND   
193                      Andorra          AND   
208                   Arab World          ARB   
209                   Arab World          ARB   
219                   Arab World          ARB   
220                   Arab World          ARB   
222                   Arab World          ARB   
237         United Arab Emirates          ARE   
238         United Arab Emirates          ARE   
248         United Arab Emirates          ARE   
249         United Arab Emirates          ARE   
251         United Arab Emirates          ARE   
266                    Argentina          ARG   
267                    Argentina          ARG   
277                    Argentina          ARG   
278                    Argentina          ARG   
280                    Argentina          ARG   

                                        Indicator Name Indicator Code  
5    Poverty headcount ratio at $6.85 a day (2017 P...    SI.POV.UMIC  
6    Poverty headcount ratio at national poverty li...    SI.POV.NAHC  
16   Poverty headcount ratio at $3.65 a day (2017 P...    SI.POV.LMIC  
17                                          Gini index    SI.POV.GINI  
19   Poverty headcount ratio at $2.15 a day (2017 P...    SI.POV.DDAY  
34   Poverty headcount ratio at $6.85 a day (2017 P...    SI.POV.UMIC  
35   Poverty headcount ratio at national poverty li...    SI.POV.NAHC  
45   Poverty headcount ratio at $3.65 a day (2017 P...    SI.POV.LMIC  
46                                          Gini index    SI.POV.GINI  
48   Poverty headcount ratio at $2.15 a day (2017 P...    SI.POV.DDAY  
63   Poverty headcount ratio at $6.85 a day (2017 P...    SI.POV.UMIC  
64   Poverty headcount ratio at national poverty li...    SI.POV.NAHC  
74   Poverty headcount ratio at $3.65 a day (2017 P...    SI.POV.LMIC  
75                                          Gini index    SI.POV.GINI  
77   Poverty headcount ratio at $2.15 a day (2017 P...    SI.POV.DDAY  
92   Poverty headcount ratio at $6.85 a day (2017 P...    SI.POV.UMIC  
93   Poverty headcount ratio at national poverty li...    SI.POV.NAHC  
103  Poverty headcount ratio at $3.65 a day (2017 P...    SI.POV.LMIC  
104                                         Gini index    SI.POV.GINI  
106  Poverty headcount ratio at $2.15 a day (2017 P...    SI.POV.DDAY  
121  Pov

In [19]:
# merge the index names with the interpolated years data
WB_poverty_req_corrected = pd.merge(WB_poverty_req_headers, WB_poverty_req_interpolated, left_index=True, right_index=True)
WB_poverty_req_corrected.tail(50)

Country Name Country Code  \
7429  Virgin Islands (U.S.)          VIR   
7430  Virgin Islands (U.S.)          VIR   
7440  Virgin Islands (U.S.)          VIR   
7441  Virgin Islands (U.S.)          VIR   
7443  Virgin Islands (U.S.)          VIR   
7458               Viet Nam          VNM   
7459               Viet Nam          VNM   
7469               Viet Nam          VNM   
7470               Viet Nam          VNM   
7472               Viet Nam          VNM   
7487                Vanuatu          VUT   
7488                Vanuatu          VUT   
7498                Vanuatu          VUT   
7499                Vanuatu          VUT   
7501                Vanuatu          VUT   
7516                  World          WLD   
7517                  World          WLD   
7527                  World          WLD   
7528                  World          WLD   
7530                  World          WLD   
7545                  Samoa          WSM   
7546                  Samoa          WSM   
7556                  Samoa          WSM   
7557                  Samoa          WSM   
7559                  Samoa          WSM   
7574                 Kosovo          XKX   
7575                 Kosovo          XKX   
7585                 Kosovo          XKX   
7586                 Kosovo          XKX   
7588                 Kosovo          XKX   
7603            Yemen, Rep.          YEM   
7604            Yemen, Rep.          YEM   
7614            Yemen, Rep.          YEM   
7615            Yemen, Rep.          YEM   
7617            Yemen, Rep.          YEM   
7632           South Africa          ZAF   
7633           South Africa          ZAF   
7643           South Africa          ZAF   
7644           South Africa          ZAF   
7646           South Africa          ZAF   
7661                 Zambia          ZMB   
7662                 Zambia          ZMB   
7672                 Zambia          ZMB   
7673                 Zambia          ZMB   
7675                 Zambia          ZMB   
7690               Zimbabwe          ZWE   
7691               Zimbabwe          ZWE   
7701               Zimbabwe          ZWE   
7702               Zimbabwe          ZWE   
7704               Zimbabwe          ZWE   

                                         Indicator Name Indicator Code  1996  \
7429  Poverty headcount ratio at $6.85 a day (2017 P...    SI.POV.UMIC   NaN   
7430  Poverty headcount ratio at national poverty li...    SI.POV.NAHC   NaN   
7440  Poverty headcount ratio at $3.65 a day (2017 P...    SI.POV.LMIC   NaN   
7441                                         Gini index    SI.POV.GINI   NaN   
7443  Poverty headcount ratio at $2.15 a day (2017 P...    SI.POV.DDAY   NaN   
7458  Poverty headcount ratio at $6.85 a day (2017 P...    SI.POV.UMIC 89.00   
7459  Poverty headcount ratio at national poverty li...    SI.POV.NAHC  9.20   
7469  Poverty headcount ratio at $3.65 a day (2017 P...    SI.POV.LMIC 63.40   
7470                                         Gini index    SI.POV.GINI 35.40   
7472  Poverty headcount ratio at $2.15 a day (2017 P...    SI.POV.DDAY 24.40   
7487  Poverty headcount ratio at $6.85 a day (2017 P...    SI.POV.UMIC 78.40   
7488  Poverty headcount ratio at national poverty li...    SI.POV.NAHC 15.90   
7498  Poverty headcount ratio at $3.65 a day (2017 P...    SI.POV.LMIC 42.00   
7499                                         Gini index    SI.POV.GINI 37.40   
7501  Poverty headcount ratio at $2.15 a day (2017 P...    SI.POV.DDAY 14.70   
7516  Poverty headcount ratio at $6.85 a day (2017 P...    SI.POV.UMIC 70.00   
7517  Poverty headcount ratio at national poverty li...    SI.POV.NAHC   NaN   
7527  Poverty headcount ratio at $3.65 a day (2017 P...    SI.POV.LMIC 53.40   
7528                                         Gini index    SI.POV.GINI   NaN   
7530  Poverty headcount ratio at $2.15 a day (2017 P...    SI.POV.DDAY 31.30   
7545  Poverty headcount ratio at $6.85 a day (2017 P...    SI.POV.UMIC 46.70   
7546  Pove

Dataframe has been successfully interpolated with a maximum 5 year limit for the economic data required for the study.

### e) Tidy Data Principles

MELT: Each year is an observation and should be in a column called "Year".

PIVOT: The five indicators (currently in 'Indicator Name') are separate variables, and should ben five columns, with the numerical values being the observation in these columns.

Country and Country Code are correctly column headers.

The dataframe should be presented in the following way:

(All values are per capita)

| Country | Year | Indicator 1 | Indicator 2 | Indicator 3 | Indicator 4 | Indicator 5 |
|:--------|:-----|:------------|:------------|:------------|:------------|:------------|
| Aruba   | 1996 | XXX         | XXX         | XXX         | XXX         | XXX         |
| Aruba   | 1997 | XXX         | XXX         | XXX         | XXX         | XXX         |
| Aruba   | 1998 | XXX         | XXX         | XXX         | XXX         | XXX         |
| Aruba   | 1999 | XXX         | XXX         | XXX         | XXX         | XXX         |

The indicators are:

"Poverty headcount ratio at national poverty lines (% of population)"

"Poverty headcount ratio at $6.85 a day (2017 PPP) (% of population)"

"Poverty headcount ratio at $2.15 a day (2017 PPP) (% of population)"

"Poverty headcount ratio at $3.65 a day (2017 PPP) (% of population)"

"Gini index"

This will also make merging with other dataframes easier, and give greater versatility to the visualisations made in the future.


In [20]:
# First use a MELT to turn the years into a variable, the recorded value of the indicator will temporarirly be called "value":
WB_poverty_req_corrected_melt = WB_poverty_req_corrected.melt(['Country Name','Country Code','Indicator Name','Indicator Code'], var_name = "Year", value_name = "value")

In [21]:
WB_poverty_req_corrected_melt.head(50)

Country Name Country Code  \
0                         Aruba          ABW   
1                         Aruba          ABW   
2                         Aruba          ABW   
3                         Aruba          ABW   
4                         Aruba          ABW   
5   Africa Eastern and Southern          AFE   
6   Africa Eastern and Southern          AFE   
7   Africa Eastern and Southern          AFE   
8   Africa Eastern and Southern          AFE   
9   Africa Eastern and Southern          AFE   
10                  Afghanistan          AFG   
11                  Afghanistan          AFG   
12                  Afghanistan          AFG   
13                  Afghanistan          AFG   
14                  Afghanistan          AFG   
15   Africa Western and Central          AFW   
16   Africa Western and Central          AFW   
17   Africa Western and Central          AFW   
18   Africa Western and Central          AFW   
19   Africa Western and Central          AFW   
20                       Angola          AGO   
21                       Angola          AGO   
22                       Angola          AGO   
23                       Angola          AGO   
24                       Angola          AGO   
25                      Albania          ALB   
26                      Albania          ALB   
27                      Albania          ALB   
28                      Albania          ALB   
29                      Albania          ALB   
30                      Andorra          AND   
31                      Andorra          AND   
32                      Andorra          AND   
33                      Andorra          AND   
34                      Andorra          AND   
35                   Arab World          ARB   
36                   Arab World          ARB   
37                   Arab World          ARB   
38                   Arab World          ARB   
39                   Arab World          ARB   
40         United Arab Emirates          ARE   
41         United Arab Emirates          ARE   
42         United Arab Emirates          ARE   
43         United Arab Emirates          ARE   
44         United Arab Emirates          ARE   
45                    Argentina          ARG   
46                    Argentina          ARG   
47                    Argentina          ARG   
48                    Argentina          ARG   
49                    Argentina          ARG   

                                       Indicator Name Indicator Code  Year  \
0   Poverty headcount ratio at $6.85 a day (2017 P...    SI.POV.UMIC  1996   
1   Poverty headcount ratio at national poverty li...    SI.POV.NAHC  1996   
2   Poverty headcount ratio at $3.65 a day (2017 P...    SI.POV.LMIC  1996   
3                                          Gini index    SI.POV.GINI  1996   
4   Poverty headcount ratio at $2.15 a day (2017 P...    SI.POV.DDAY  1996   
5   Poverty headcount ratio at $6.85 a day (2017 P...    SI.POV.UMIC  1996   
6   Poverty headcount ratio at national poverty li...    SI.POV.NAHC  1996   
7   Poverty headcount ratio at $3.65 a day (2017 P...    SI.POV.LMIC  1996   
8                                          Gini index    SI.POV.GINI  1996   
9   Poverty headcount ratio at $2.15 a day (2017 P...    SI.POV.DDAY  1996   
10  Poverty headcount ratio at $6.85 a day (2017 P...    SI.POV.UMIC  1996   
11  Poverty headcount ratio at national poverty li...    SI.POV.NAHC  1996   
12  Poverty headcount ratio at $3.65 a day (2017 P...    SI.POV.LMIC  1996   
13                                         Gini index    SI.POV.GINI  1996   
14  Poverty headcount ratio at $2.15 a day (2017 P...    SI.POV.DDAY  1996   
15  Poverty headcount ratio at $6.85 a day (2017 P...    SI.POV.UMIC  1996   
16  Poverty headcount ratio at national poverty li...    SI.POV.NAHC  1996   
17  Poverty headcount ratio at $3.65 a day (2017 P...    SI.POV.LMIC  1996   
18                                         Gini index    SI.POV.GINI  1996   
19  Povert

The dataframe has had the years conrrectly converted to variables, and each year is an observation.

In [22]:
# Second use PIVOT to convert the Indicators into separate variables, and not observations
WB_poverty_req_corrected_melt_pivot = WB_poverty_req_corrected_melt.pivot_table(
                                            index = ['Country Name', 'Year'], 
                                            columns = 'Indicator Name', 
                                            values = 'value').reset_index()

WB_poverty_req_corrected_melt_pivot.head(500)

Indicator Name            Country Name  Year  Gini index  \
0                          Afghanistan  1996         NaN   
1                          Afghanistan  1997         NaN   
2                          Afghanistan  1998         NaN   
3                          Afghanistan  1999         NaN   
4                          Afghanistan  2000         NaN   
5                          Afghanistan  2001         NaN   
6                          Afghanistan  2002         NaN   
7                          Afghanistan  2003         NaN   
8                          Afghanistan  2004         NaN   
9                          Afghanistan  2005         NaN   
10                         Afghanistan  2006         NaN   
11                         Afghanistan  2007         NaN   
12                         Afghanistan  2008         NaN   
13                         Afghanistan  2009         NaN   
14                         Afghanistan  2010         NaN   
15                         Afghanistan  2011         NaN   
16                         Afghanistan  2012         NaN   
17                         Afghanistan  2013         NaN   
18                         Afghanistan  2014         NaN   
19                         Afghanistan  2015         NaN   
20                         Afghanistan  2016         NaN   
21                         Afghanistan  2017         NaN   
22                         Afghanistan  2018         NaN   
23                         Afghanistan  2019         NaN   
24                         Afghanistan  2020         NaN   
25                         Afghanistan  2021         NaN   
26                             Albania  1996       27.00   
27                             Albania  1997       27.78   
28                             Albania  1998       28.57   
29                             Albania  1999       29.35   
30                             Albania  2000       30.13   
31                             Albania  2001       30.92   
32                             Albania  2002       31.70   
33                             Albania  2003       31.33   
34                             Albania  2004       30.97   
35                             Albania  2005       30.60   
36                             Albania  2006       30.40   
37                             Albania  2007       30.20   
38                             Albania  2008       30.00   
39                             Albania  2009       29.75   
40                             Albania  2010       29.50   
41                             Albania  2011       29.25   
42                             Albania  2012       29.00   
43                             Albania  2013       31.80   
44                             Albania  2014       34.60   
45                             Albania  2015       32.80   
46                             Albania  2016       33.70   
47                             Albania  2017       33.10   
48                             Albania  2018       30.10   
49                             Albania  2019       30.10   
50                             Albania  2020       29.40   
51                             Albania  2021       29.40   
52                             Algeria  1996       27.60   
53                             Algeria  1997       27.60   
54                             Algeria  1998       27.60   
55                             Algeria  1999       27.60   
56                             Algeria  2000       27.60   
57                             Algeria  2001       27.60   
58                             Algeria  2002       27.60   
59                             Algeria  2003       27.60   
60                             Algeria  2004       27.60   
61                             Algeria  2005       27.60   
62                             Algeria  2006       27.60   
63                             Algeria  2007       27.60   
64                             Algeria  2008       27.60   
65                             Algeria  

The pivoting has correctly converted the data to the standardised Tidy Data norms.

In [23]:
# After the changes the dataframe haas been converted to a list of Tuples.
# This needs to be converted back to a dataframe.
WB_poverty_req_corrected_melt_pivot = pd.DataFrame(WB_poverty_req_corrected_melt_pivot)

In [24]:
WB_poverty_req_corrected_melt_pivot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4784 entries, 0 to 4783
Data columns (total 7 columns):
 #   Column                                                               Non-Null Count  Dtype  
---  ------                                                               --------------  -----  
 0   Country Name                                                         4784 non-null   object 
 1   Year                                                                 4784 non-null   object 
 2   Gini index                                                           4316 non-null   float64
 3   Poverty headcount ratio at $2.15 a day (2017 PPP) (% of population)  4680 non-null   float64
 4   Poverty headcount ratio at $3.65 a day (2017 PPP) (% of population)  4680 non-null   float64
 5   Poverty headcount ratio at $6.85 a day (2017 PPP) (% of population)  4680 non-null   float64
 6   Poverty headcount ratio at national poverty lines (% of population)  4030 non-null   float64
dtypes: floa

## 04 Save data to a cleaned data folder

In [25]:
WB_poverty_req_corrected_melt_pivot.to_csv(os.path.join(pathData, 'World Bank Cleaned', 'poverty_clean.csv'), index=False)